version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banknifty
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@db:5432/banknifty
      REDIS_URL: redis://redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

volumes:
  db-data:
