version: '3.8'
services:
  backend:
    volumes:
      - ../backend:/app
    environment:
      NODE_ENV: development
    command: npm run dev
  frontend:
    volumes:
      - ../frontend:/app
    environment:
      NODE_ENV: development
    command: npm run dev
