name: CI Smoke

on:
  push:
    branches: [ feature/** ]
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI smoke run for feature branch" > smoke.txt
      - uses: actions/upload-artifact@v4
        with:
          name: smoke-artifact
          path: smoke.txt
