name: CI

on:
  push:
    branches: [ main, 'tests/**', 'cleanup/**' ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
        working-directory: ./backend
      - name: Build (TypeScript)
        run: npm run build
        working-directory: ./backend
      - name: Run tests
        run: npm run test:ts -- --runInBand
        working-directory: ./backend
