name: Infra Validation

on:
  pull_request:
    paths:
      - 'docker-compose.yml'
      - 'backend/**'
      - '.github/**'
  workflow_dispatch: {}

jobs:
  infra-validate:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: banknifty
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 5s --health-timeout 5s --health-retries 5
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping" --health-interval 5s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Validate defaults
        working-directory: backend
        run: npm run validate:defaults

      - name: Run DB Migrations
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/banknifty
        working-directory: backend
        run: |
          npm run db:migrate

      - name: Run Seeders
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/banknifty
        working-directory: backend
        run: |
          node ./scripts/run_seeders.js

      - name: Run tests
        working-directory: backend
        run: npm test

      - name: Smoke healthcheck
        run: |
          echo "Waiting up to 15s for service on tcp:8080..."
          npx wait-on --timeout 15000 tcp:8080 || echo "wait-on timed out, continuing"
          echo "Attempting HTTP GET /health"
          if curl --fail --max-time 5 http://localhost:8080/health; then
            echo "Healthcheck succeeded"
          else
            echo "Healthcheck failed or service unavailable (non-fatal)"
          fi
