name: Release

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install
        run: npm ci
        working-directory: ./backend
      - name: Build
        run: npm run build
        working-directory: ./backend
      - name: Zip dist
        run: |
          cd backend
          zip -r ../backend-dist-$(date +"%Y%m%d%H%M%S").zip dist
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: backend-dist-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
