name: Workflow Schema Lint

on:
  pull_request_target:
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run actionlint via docker run (fallback)
        # Run the actionlint Docker image directly via `docker run` to avoid
        # action resolution issues in PR contexts and ensure reliable execution.
        run: |
          docker run --rm -v "${{ github.workspace }}":/work nektos/actionlint:v1 /work/.github/workflows
