name: Workflow Schema Lint

on:
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run actionlint
        uses: nektos/actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
