name: Workflow Schema Lint

on:
  pull_request_target:
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run actionlint (docker image)
        # Use the Docker image directly to avoid Marketplace resolution issues
        uses: docker://nektos/actionlint:v1
        with:
          args: ".github/workflows"
